- hosts: terraform-ansible
  tasks: 
    - name: Instalando  o python3, virtualenv
      apt: 
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
    - name: Instalando dependencias com pip (Django e Djano Rest)
      pip: 
        virtualenv: /home/ubuntu/tcc/venv
        name: 
          - django
          - djangorestframework



# ansible-playbook playbook.yml -u ubuntu --private-key iac-alura.pem -i hosts.yml