- hosts: terraform-ansible
  tasks: 
    - name: Instalando  o python3, virtualenv
      apt: 
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
    - name: Instalando dependencias com pip (Django e Djano Rest)
      pip: 
        virtualenv: /home/ubuntu/tcc/venv
        name: 
          - django
          - djangorestframework
    - name: Verificando se o projeto existe
      stat: 
        path: /home/ubuntu/tcc/setup/settings.py
      register: projetoexiste
    - name: Iniciando o projeto
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
      when: not projetoexiste.stat.exists
    - name: Alterando host dos settings
      lineinfile:  #alteração em uma linha especifica de um arquivo em texto
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS' 
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes


# ansible-playbook env/Dev/playbook.yml -u ubuntu --private-key env/Dev/Iac-DEV.pem -i hosts.yml